#!/bin/bash
R -e 'install.packages("httr")'
R -e 'BiocManager::install("SummarizedExperiment")'
R -e 'install.packages("pvr_pkg/Matrix_1.6-5.tar.gz", repos=NULL, type="source")'
R -e 'BiocManager::install("ggplot2")'
R -e 'install.packages("pvr_pkg/httpuv_1.6.0.tar.gz"", repos=NULL, type="source")'
R -e 'install.packages("ade4")'
R -e 'install.packages("biomformat")'
R -e 'BiocManager::install("igraph", force = TRUE, update = FALSE)'
R -e 'BiocManager::install("multtest", force = TRUE, update = FALSE)'
R -e 'install.packages("vegan")'
R -e 'install.packages("pvr_pkg/RProtoBufLib_2.14.1.tar.gz", repos=NULL, type="source")'
R -e 'remotes::install_github("RGLab/cytolib")'
R -e 'remotes::install_github("RGLab/flowcore")'
R -e 'BiocManager::install("AnnotationDbi", force = TRUE, update = FALSE)'
R -e 'BiocManager::install("igraph", force = TRUE, update = FALSE)'
R -e 'BiocManager::install("ggfun", force = TRUE, update = FALSE)'
R -e 'BiocManager::install("SingleCellExperiment", force = TRUE, update = FALSE)'
R -e 'BiocManager::install("phyloseq", force = TRUE, update = FALSE)'
R -e 'BiocManager::install("curl", force = TRUE, update = FALSE)'
R -e 'BiocManager::install("annotate", force = TRUE, update = FALSE)'
R -e 'BiocManager::install("BiocFileCache", force = TRUE, update = FALSE)'
R -e 'install.packages("pvr_pkg/MASS_7.3-60.tar.gz", repos=NULL, type="source")'
R -e 'BiocManager::install("aplot", force = TRUE, update = FALSE)'
R -e 'BiocManager::install("lme4", force = TRUE, update = FALSE)'
R -e 'BiocManager::install("TMB", force = TRUE, update = FALSE)'
R -e 'BiocManager::install("GenomicFeatures", force = TRUE, update = FALSE)'
R -e 'BiocManager::install("metagenomeSeq", force = TRUE, update = FALSE)'
R -e 'remotes::install_github("YuLab-SMU/ggtree")'
R -e 'remotes::install_github("YuLab-SMU/enrichplot")'
R -e 'BiocManager::install("ragg", force = TRUE, update = FALSE)'
R -e 'BiocManager::install("sctransform", force = TRUE, update = FALSE)'

